apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - keycloak/1-namespace.yaml
  - keycloak/2-keycloak-operator.yaml
  - keycloak/3-secret.yaml
  - keycloak/4-Keycloak-postgresSQL.yaml
  - keycloak/5-keycloak-instance.yaml
  - keycloak/6-keycloak-realm.yaml
